### ISSUE TITLE
Homework 2 grade

### ISSUE THREAD

**Issue by jarretrt** [yilinyang123/Machine-Learning#2]
Hey Yilin, 

There are a couple issues with your homework that still need to be corrected. 

1. Check the correlation matrix at the beginning against the text (HTF Table 3.1, page 50) again. The numbers don't quite match. 

2. There's a problem with your error() function that's resulting in an incorrect test error estimate. The correct value should be around 0.52. 

Thanks,
Ryan

**Comment by yilinyang123** [comment]
Hi Ryan, I have updated hw2, please check

**Comment by jarretrt** [comment]
Great, it looks good now! I've passed you for the assignment.
