### ISSUE TITLE
HW3 feedback

### ISSUE THREAD

**Issue by ntjames** [yilinyang123/Machine-Learning#3]
Hi @yilinyang123,

I can see your .Rmd file, but not the .md file for this assignment. Please make sure the .md is pushed to your github repo. Note that the `manipulate()` function will not work correctly for a .md file. You will need to modify that section of code to create static plots of the AIC, BIC, training and testing errors for a sequence of tuning parameter values.

**Comment by yilinyang123** [comment]
Hi Nathan,
I have pushed the markdown file to hw3. Thank you for your time.

**Comment by ntjames** [comment]
Your updated code looks good and I've marked it as a pass. However, note that for the interpretation in question 6, models with smaller k values are _more_ complex. Using the 1-sd rule, you should choose the model with the _largest_ k value whose mean CV test error is below the dotted line. Based on your plot, k=22 would be an appropriate tuning parameter.
